# Part 2. Dataframe preparation

Once we have downloaded all the datasets we will be using in our project, the first thing we should do is preparing the dataframe we will be working on.

The main goal of this notebook is to download the bridge datasets for the years previous to 2018, prepare the data using new features and merge this new input data into the 2018's dataset we have created in the previous dataset.

In [2]:
# Importing modules
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns',None)

In [1]:
rating_cols = ['STATE_CODE_001','STRUCTURE_NUMBER_008','DECK_COND_058','SUPERSTRUCTURE_COND_059','SUBSTRUCTURE_COND_060']

In [4]:
# Function for new variable: Total Rating (TR)

def TotalRating(row):
    dr = row['DECK_COND_058']
    supr = row['SUPERSTRUCTURE_COND_059']
    subr = row['SUBSTRUCTURE_COND_060']
    minval = min(dr, supr, subr)
    maxval = max(dr, supr, subr)
   
    if minval <= 4:
        rating = minval
        
    elif minval >= 8:
        rating = (dr+supr+subr)/3
        
    else:
        medval = dr+subr+supr-minval-maxval
        rating = 0.5*minval+0.2*maxval+0.3*medval

    return rating

In [6]:
filenames = []
for year in range(2008,2018):
    year = str(year)
    path = "./data/"+year+"hwybronlyonefile.zip"
    filenames.append(path)

In [7]:
filenames

['./data/2008hwybronlyonefile.zip',
 './data/2009hwybronlyonefile.zip',
 './data/2010hwybronlyonefile.zip',
 './data/2011hwybronlyonefile.zip',
 './data/2012hwybronlyonefile.zip',
 './data/2013hwybronlyonefile.zip',
 './data/2014hwybronlyonefile.zip',
 './data/2015hwybronlyonefile.zip',
 './data/2016hwybronlyonefile.zip',
 './data/2017hwybronlyonefile.zip']

In [5]:
def createTR (filename,colname):
        
    # Create dataframes
    df = pd.read_csv(filename, compression = 'zip',sep = ',',encoding='latin-1',usecols = rating_cols)
    
    # Remove 'N'
    df = df[(df['DECK_COND_058']!='N') & (df['SUPERSTRUCTURE_COND_059']!='N') & (df['SUBSTRUCTURE_COND_060']!='N') ]
    
    # To numeric
    df['DECK_COND_058'] = pd.to_numeric(df['DECK_COND_058'])
    df['SUPERSTRUCTURE_COND_059'] = pd.to_numeric(df['SUPERSTRUCTURE_COND_059'])
    df['SUBSTRUCTURE_COND_060'] = pd.to_numeric(df['SUBSTRUCTURE_COND_060'])
    
    # Remove nulls
    df.dropna(inplace=True)
    
    # Creamos la columna con el Total Rating para cada a√±o
    df[colname] = df.apply(lambda row: TotalRating(row),axis=1)
    
    return df

In [19]:
df17 = createTR('./data/2017hwybronlyonefile.zip','TR17')

/home/dsc/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3185: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):

In [20]:
df17.to_csv (r'./df17.csv', index = None, header=True)

In [21]:
df16 = createTR('./data/2016hwybronlyonefile.zip','TR16')

In [22]:
df16.to_csv (r'./df16.csv', index = None, header=True)

In [23]:
df15 = createTR('./data/2015hwybronlyonefile.zip','TR15')
df15.to_csv (r'./df15.csv', index = None, header=True)

In [24]:
df14 = createTR('./data/2014hwybronlyonefile.zip','TR14')
df14.to_csv (r'./df14.csv', index = None, header=True)

In [25]:
df13 = createTR('./data/2013hwybronlyonefile.zip','TR13')
df13.to_csv (r'./df13.csv', index = None, header=True)

In [26]:
df12 = createTR('./data/2012hwybronlyonefile.zip','TR12')
df12.to_csv (r'./df12.csv', index = None, header=True)

In [27]:
df11 = createTR('./data/2011hwybronlyonefile.zip','TR11')
df11.to_csv (r'./df11.csv', index = None, header=True)

In [28]:
df10 = createTR('./data/2010hwybronlyonefile.zip','TR10')
df10.to_csv (r'./df10.csv', index = None, header=True)

In [59]:
df09 = createTR('./data/2009hwybronlyonefile.zip','TR09')
df09.to_csv (r'./df09.csv', index = None, header=True)

/home/dsc/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3185: DtypeWarning: Columns (1,66,67,68) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):

In [60]:
df08 = createTR('./data/2008hwybronlyonefile.zip','TR08')
df08.to_csv (r'./df08.csv', index = None, header=True)

# DESCARGAR LOS CSV A PARTIR DE AQUI

In [6]:
df17 = pd.read_csv('df17.csv')
df16 = pd.read_csv('df16.csv')
df15 = pd.read_csv('df15.csv')
df14 = pd.read_csv('df14.csv')
df13 = pd.read_csv('df13.csv')
df12 = pd.read_csv('df12.csv')
df11 = pd.read_csv('df11.csv')
df10 = pd.read_csv('df10.csv')
df09 = pd.read_csv('df09.csv')
df08 = pd.read_csv('df08.csv')

In [7]:
# Vamos a leer el dataset del 2018 para hacer el join
total18_fil = pd.read_csv('total18_fil.csv')

In [8]:
df18 = total18_fil
df18['TR18'] = df18.apply(lambda row: TotalRating(row),axis=1)

In [9]:
df18.shape

(166209, 25)

In [10]:
df_list = [df18,df17,df16,df15,df14,df13,df12,df11,df10,df09,df08] 

for df in df_list:
    df.drop(['DECK_COND_058','SUPERSTRUCTURE_COND_059','SUBSTRUCTURE_COND_060'], axis=1, inplace = True)

In [11]:
df_all = df18

for df in df_list[1:]:
    df_all = pd.merge(df_all, df, how='left', on=['STATE_CODE_001','STRUCTURE_NUMBER_008'])

In [12]:
df_all.head(10)

,STATE_CODE_001,STRUCTURE_NUMBER_008,TRAFFIC_LANES_ON_028A,MEDIAN_CODE_033,DEGREES_SKEW_034,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,MAIN_UNIT_SPANS_045,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,...,TR17,TR16,TR15,TR14,TR13,TR12,TR11,TR10,TR09,TR08
0,1,000013771700120,2,0,0,steel,2,1,17.7,18.9,...,6.5,7.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
1,1,000040,4,2,0,steel,2,1,8.2,8.2,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
2,1,000050,2,0,20,steel,2,1,9.4,9.4,...,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5
3,1,000060,3,0,0,concrete,2,3,10.4,34.7,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0
4,1,000083,1,0,20,steel,2,2,3.7,7.3,...,6.2,6.2,6.2,6.2,6.2,4.0,4.0,4.0,4.0,4.0
5,1,000085,1,0,0,steel,2,8,4.0,18.6,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
6,1,000136,1,0,0,steel,2,5,6.0,30.3,...,4.0,4.0,5.2,5.2,5.2,5.2,5.2,6.0,6.0,6.0
7,1,000138,1,0,0,steel,2,1,12.2,12.2,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
8,1,000147,1,0,0,steel,2,1,6.1,7.0,...,5.2,5.2,5.2,5.2,6.0,6.0,6.0,6.0,6.0,6.0
9,1,000163,1,0,0,steel,2,1,12.2,12.2,...,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5,5.5

In [12]:
df_all.shape

(167516, 32)

In [14]:
# La raz√≥n por la que hemos ampliado el dataset a todos los puentes es porque en Pennsylvania, 
# donde inicialmente lo ibamos a hacer, cuando hacemos el join nos quedamos con 5 puentes con rating
# v√°lido de 2010 hacia atr√°s.

df_all[(df_all['STATE_CODE_001'] == 42)].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3912 entries, 121633 to 125544
Data columns (total 33 columns):
STATE_CODE_001            3912 non-null int64
STRUCTURE_NUMBER_008      3912 non-null object
TRAFFIC_LANES_ON_028A     3912 non-null int64
MEDIAN_CODE_033           3912 non-null int64
DEGREES_SKEW_034          3912 non-null int64
STRUCTURE_KIND_043A       3912 non-null object
STRUCTURE_TYPE_043B       3912 non-null int64
MAIN_UNIT_SPANS_045       3912 non-null int64
MAX_SPAN_LEN_MT_048       3912 non-null float64
STRUCTURE_LEN_MT_049      3912 non-null float64
DECK_WIDTH_MT_052         3912 non-null float64
SURFACE_TYPE_108A         3912 non-null object
YEAR_BUILT_027            3912 non-null float64
AGE                       3912 non-null float64
DESIGN_LOAD_031           3912 non-null object
TRUCK_ADT                 3912 non-null float64
MAINTENANCE_021           3912 non-null float64
FUNCTIONAL_CLASS_026      3912 non-null object
WATERWAY_EVAL_071         3912 non-null object
YEAR_RECONSTRUCTED_106    3912 non-null float64
longitude                 3912 non-null float64
latitude                  3912 non-null float64
TR18                      3912 non-null float64
TR17                      3780 non-null float64
TR16                      3818 non-null float64
TR15                      3407 non-null float64
TR14                      3502 non-null float64
TR13                      3678 non-null float64
TR12                      3559 non-null float64
TR11                      3363 non-null float64
TR10                      5 non-null float64
TR09                      5 non-null float64
TR08                      5 non-null float64
dtypes: float64(21), int64(6), object(6)
memory usage: 1.0+ MB

In [18]:
# Si consideramos todo el dataset vamos perdiendo datos pero seguimos con un n√∫mero considerable de entradas

df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 169366 entries, 0 to 169365
Data columns (total 33 columns):
STATE_CODE_001            169366 non-null int64
STRUCTURE_NUMBER_008      169366 non-null object
LAT_016                   169366 non-null float64
LONG_017                  169366 non-null float64
TRAFFIC_LANES_ON_028A     169366 non-null int64
MEDIAN_CODE_033           169366 non-null int64
DEGREES_SKEW_034          169366 non-null int64
STRUCTURE_KIND_043A       169366 non-null object
STRUCTURE_TYPE_043B       169366 non-null int64
MAIN_UNIT_SPANS_045       169366 non-null int64
MAX_SPAN_LEN_MT_048       169366 non-null float64
STRUCTURE_LEN_MT_049      169366 non-null float64
DECK_WIDTH_MT_052         169366 non-null float64
SURFACE_TYPE_108A         169366 non-null object
YEAR_BUILT_027            169366 non-null float64
AGE                       169366 non-null float64
DESIGN_LOAD_031           169366 non-null object
TRUCK_ADT                 169366 non-null float64
MAINTENANCE_021           169366 non-null float64
FUNCTIONAL_CLASS_026      169366 non-null object
WATERWAY_EVAL_071         169366 non-null object
YEAR_RECONSTRUCTED_106    169366 non-null float64
TR18                      169366 non-null float64
TR17                      162762 non-null float64
TR16                      157751 non-null float64
TR15                      150587 non-null float64
TR14                      150570 non-null float64
TR13                      147704 non-null float64
TR12                      147657 non-null float64
TR11                      143108 non-null float64
TR10                      135673 non-null float64
TR09                      131703 non-null float64
TR08                      131397 non-null float64
dtypes: float64(21), int64(6), object(6)
memory usage: 43.9+ MB

In [13]:
tr_cols = list(df_all.columns)[-11:][::-1]
tr_cols

['TR08',
 'TR09',
 'TR10',
 'TR11',
 'TR12',
 'TR13',
 'TR14',
 'TR15',
 'TR16',
 'TR17',
 'TR18']

In [14]:
years_rated = len(df_list)
years_rated

11

In [15]:
# Drop all the rows where half of the ratings are missing

df_all.dropna(subset= tr_cols, thresh=(years_rated // 2 + 1), inplace=True)

In [16]:
df_all.shape

(147720, 32)

In [19]:
df_all['TR08'].isna().value_counts()

False    128966
True      19018
Name: TR08, dtype: int64

In [17]:
# For the missing values in the rating columns that are left, we will equal them to the rating of the previous year
# Therefore, we should have all the rating from the first year we are considering

df_all.dropna(subset = [tr_cols[1]], inplace= True)

In [18]:
df_all.shape

(129630, 32)

In [19]:
for n in range(len(tr_cols)-1):
    df_all[tr_cols[n+1]] = df_all.apply(lambda row: 
                                        row[tr_cols[n]] if np.isnan(row[tr_cols[n+1]]) else row[tr_cols[n+1]],
                                        axis=1)

In [20]:
df_all.sample(20)

,STATE_CODE_001,STRUCTURE_NUMBER_008,TRAFFIC_LANES_ON_028A,MEDIAN_CODE_033,DEGREES_SKEW_034,STRUCTURE_KIND_043A,MAIN_UNIT_SPANS_045,MAX_SPAN_LEN_MT_048,STRUCTURE_LEN_MT_049,DECK_WIDTH_MT_052,SURFACE_TYPE_108A,YEAR_BUILT_027,YEAR_RECONSTRUCTED_106,AGE,DESIGN_LOAD_031,TRUCK_ADT,MAINTENANCE_021,FUNCTIONAL_CLASS_026,WATERWAY_EVAL_071,LONGITUDE,LATITUDE,TR18,TR17,TR16,TR15,TR14,TR13,TR12,TR11,TR10,TR09,TR08
90827,36,000000001062791,2,0,10,steel,1,33.5,34.7,13.1,concrete,1970.0,0.0,49.0,heavy,1005.75,1.0,rural,none,-78.467334,42.066001,7.0,7.0,7.0,7.0,7.0,7.0,7.5,7.5,7.5,7.5,7.5
24808,13,000000029950910,2,1,0,concrete,7,12.2,85.3,12.4,concrete,2005.0,0.0,14.0,heavy,936.60,1.0,rural,low,-82.271667,31.179336,7.0,6.5,6.5,7.0,7.0,7.5,7.5,7.5,7.5,8.0,8.0
89693,36,000000001036080,2,0,30,concrete,2,28.5,58.8,12.8,concrete,2001.0,0.0,18.0,heavy,373.74,1.0,urban,none,-73.472335,41.024168,8.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
66198,28,SA7400000000008,2,0,0,concrete,6,24.4,121.9,9.1,concrete,1982.0,0.0,37.0,light,29.60,2.0,rural,high,-90.125336,31.013669,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.5,7.5
64257,28,310040704903040,2,0,0,concrete,5,12.2,61.4,10.0,none,1991.0,0.0,28.0,heavy,79.20,1.0,rural,low,-89.374168,33.235669,7.0,7.2,7.2,7.2,7.2,8.0,8.0,8.0,8.0,8.0,8.0
64029,28,310017801700930,2,0,0,concrete,5,12.2,49.4,10.0,none,1990.0,0.0,29.0,heavy,469.00,1.0,rural,high,-89.451002,34.543834,7.2,7.2,7.2,7.2,7.5,7.5,8.0,8.0,8.0,8.0,8.0
24729,13,000000029550590,2,0,0,steel,2,6.4,12.5,8.5,concrete,1977.0,0.0,42.0,other,3.50,2.0,rural,low,-85.246336,34.535000,5.2,5.2,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0
116588,40,234630000000000,2,0,0,concrete,1,24.7,25.3,8.7,concrete,1992.0,0.0,27.0,heavy,3.60,2.0,rural,low,-99.589169,36.328834,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2,7.2
14949,9,03338,2,1,23,concrete,1,29.3,30.8,13.3,bituminous,1966.0,0.0,53.0,heavy,933.00,1.0,urban,none,-72.237168,41.202500,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5,6.5
33867,18,42290,8,2,99,steel,4,35.1,161.6,40.0,concrete,1973.0,1996.0,23.0,heavy,18574.00,1.0,urban,none,-86.092835,39.452001,6.5,4.0,4.0,4.0,4.0,4.0,6.0,6.0,6.5,6.5,7.0
128757,47,03SR0690013,2,0,0,concrete,3,12.2,36.3,9.3,none,2000.0,0.0,19.0,heavy,81.00,1.0,rural,low,-88.072502,35.558001,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.5
108612,39,4860993,2,0,12,steel,3,12.2,38.4,11.3,concrete,2012.0,0.0,7.0,heavy,0.00,4.0,urban,high,-83.349167,41.379834,9.0,9.0,9.0,9.0,9.0,9.0,3.0,4.0,4.0,4.0,4.0
88490,36,000000001002770,2,0,45,steel,2,41.5,83.2,11.9,concrete,1995.0,0.0,24.0,heavy,308.56,5.0,rural,none,-74.555168,43.008000,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.2,7.2,7.2
100345,37,1150300,2,0,20,steel,1,11.9,12.5,6.1,bituminous,1966.0,0.0,53.0,light,21.60,1.0,rural,high,-82.342169,35.472168,4.0,4.0,4.0,4.0,4.0,4.0,7.0,7.0,7.5,5.6,5.6
10388,6,53C0328,4,0,39,steel,1,13.7,14.3,15.1,concrete,1928.0,0.0,91.0,light,3089.40,2.0,rural,none,-118.352002,34.257002,6.2,6.2,5.7,5.7,5.7,5.7,6.2,6.2,6.2,6.2,6.2
160539,55,B09014500000000,2,0,25,concrete,1,13.4,14.1,11.6,concrete,1991.0,0.0,28.0,heavy,132.00,1.0,rural,low,-91.326336,45.057336,6.5,6.5,6.5,6.5,6.5,6.5,6.5,7.0,7.0,7.0,7.0
24962,13,000000031700090,2,0,0,steel,3,31.7,229.2,12.9,concrete,1971.0,0.0,48.0,heavy,271.80,1.0,rural,low,-82.462502,33.583669,5.2,5.2,5.2,5.2,5.2,5.2,5.2,5.2,5.2,5.2,5.2
78408,31,C001302705,2,0,30,steel,1,18.0,18.3,7.5,concrete,1980.0,0.0,39.0,other,0.00,2.0,rural,high,-96.130000,40.472000,6.5,6.5,6.5,7.0,7.0,7.0,7.0,7.5,7.5,7.5,7.5
52419,24,100000100128014,2,0,3,steel,3,14.3,36.9,12.8,concrete,1968.0,0.0,51.0,heavy,7580.80,1.0,urban,none,-77.262167,39.239167,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
70676,29,24254,2,0,0,steel,1,6.7,7.6,8.8,bituminous,1987.0,0.0,32.0,other,224.50,2.0,rural,high,-90.570668,38.503502,4.0,4.0,4.0,5.5,5.5,5.5,5.5,5.5,5.5,6.0,6.0

In [21]:
# Function that creates the deterioration rate, which is the mean of the differences between ratings every year

def det_formula(row):
    
    m=0
    cont_rehab = 0

    for i in range(1,len(tr_cols)):
        dif = row[tr_cols[i-1]]-row[tr_cols[i]]
        
        if dif >= 0: 
            m += dif
            
        else:
            dif = 0
            cont_rehab+=1
            m += dif
            
    return m/(i-cont_rehab)

In [22]:
df_all['DETERIORATION_RATE'] = df_all.apply(lambda row: det_formula(row), axis=1)

In [23]:
# A deterioration rate of 0 seems unreasonable in a 10 years gap.
(df_all['DETERIORATION_RATE']==0).value_counts()

False    91520
True     38110
Name: DETERIORATION_RATE, dtype: int64

In [24]:
# There are 38237 bridges that seem to have no deterioration in 10 years.
# We will drop out those bridges, that might have had false input data from the inspection engineer
df_all = df_all.loc[df_all['DETERIORATION_RATE'] > 0]

In [25]:
# Final dataset
df_all.shape

(91520, 33)

In [26]:
# Save to csv

df_all.to_csv (r'./df_all.csv', index = None, header=True)